MembershipReboot.HotTowel/Areas/UserAccount/Controllers/ChangePasswordController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BrockAllen.MembershipReboot;
using MembershipReboot.HotTowel.Areas.UserAccount.Models;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    [Authorize]
    public class ChangePasswordController : Controller
    {
        UserAccountService userAccountService;
        public ChangePasswordController(UserAccountService userAccountService)
        {
            this.userAccountService = userAccountService;
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.userAccountService != null)
                {
                    this.userAccountService.Dispose();
                    this.userAccountService = null;
                }
            }
            base.Dispose(disposing);
        }
        
        public ActionResult Index()
        {
            return View(new ChangePasswordInputModel());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ChangePasswordInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword))
                    {
                        return View("Success");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error changing password");
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(model);
        }
    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Controllers/ChangeUsernameController.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using BrockAllen.MembershipReboot;
using MembershipReboot.HotTowel.Areas.UserAccount.Models;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    [Authorize]
    public class ChangeUsernameController : Controller
    {
        UserAccountService userAccountService;
        ClaimsBasedAuthenticationService authSvc;

        public ChangeUsernameController(
            UserAccountService userAccountService, ClaimsBasedAuthenticationService authSvc)
        {
            this.userAccountService = userAccountService;
            this.authSvc = authSvc;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.userAccountService != null)
                {
                    this.userAccountService.Dispose();
                    this.userAccountService = null;
                }
            }
            base.Dispose(disposing);
        }


        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ChangeUsernameInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.ChangeUsername(User.Identity.Name, model.NewUsername);
                    this.authSvc.SignIn(model.NewUsername);
                    return RedirectToAction("Success");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View("Index", model);
        }

        public ActionResult Success()
        {
            return View("Success", (object)User.Identity.Name);
        }
    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Controllers/CloseAccountController.cs
using BrockAllen.MembershipReboot;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    [Authorize]
    public class CloseAccountController : Controller
    {
        UserAccountService userAccountService;
        public CloseAccountController(UserAccountService userAccountService)
        {
            this.userAccountService = userAccountService;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.userAccountService != null)
                {
                    this.userAccountService.Dispose();
                    this.userAccountService = null;
                }
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string button)
        {
            if (button == "yes")
            {
                try
                {
                    if (this.userAccountService.DeleteAccount(User.Identity.Name))
                    {
                        return RedirectToAction("Index", "Logout");
                    }
                    ModelState.AddModelError("", "Error closing your account");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return View();
        }

    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Controllers/LogoutController.cs
using BrockAllen.MembershipReboot;
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    public class LogoutController : Controller
    {
        ClaimsBasedAuthenticationService authSvc;
        public LogoutController(ClaimsBasedAuthenticationService authSvc)
        {
            this.authSvc = authSvc;
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.authSvc != null)
                {
                    this.authSvc.Dispose();
                    this.authSvc = null;
                }
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                authSvc.SignOut();
                return RedirectToAction("Index");
            }
            
            return View();
        }

    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Controllers/MembershipController.cs
using Breeze.WebApi;
using BrockAllen.MembershipReboot;
using MembershipReboot.HotTowel.Areas.UserAccount.Models;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    [Authorize]
    public class MembershipController : Controller
    {
        //private readonly MembershipRepository _contextProvider;

        //readonly IUserAccountRepository userAccountRepository;
        //public MembershipController(IUserAccountRepository userAccountRepository)
        //{
        //    this.userAccountRepository = userAccountRepository;
        //    _contextProvider = new MembershipRepository();
        //}

        UserAccountService userAccountService;
        ClaimsBasedAuthenticationService authSvc;

        public MembershipController(
            UserAccountService userService,
            ClaimsBasedAuthenticationService authSvc)
        {
            this.userAccountService = userService;
            this.authSvc = authSvc;
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult JsonLogin(LoginInputModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                BrockAllen.MembershipReboot.UserAccount account;
                if (userAccountService.AuthenticateWithUsernameOrEmail(model.Username, model.Password, out account))
                {
                    authSvc.SignIn(account);

                    //authSvc.SignIn(model.Username);

                    if (userAccountService.IsPasswordExpired(model.Username))
                    {
                        ModelState.AddModelError("", "The password for this account has expired.");
                    }
                    else
                    {
                        if (Url.IsLocalUrl(returnUrl))
                        {
                            return Json(new { success = true, redirect = returnUrl });
                        }
                        else
                        {
                            return Json(new { success = true, redirect = "/" });
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Username or Password");
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult JsonRegister(RegisterInputModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.CreateAccount(model.Username, model.Password, model.Email);
                    if (SecuritySettings.Instance.RequireAccountVerification)
                    {
                        return Json(new { success = true, confirmed = false, message = "You have been sent a verification email.  Follow the instructions to verify your account." });
                    }
                    else
                    {
                        return Json(new { success = true, confirmed = true, message = "You have been confirmed to login." });
                    }
                }
                catch (ValidationException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult JsonResetPassword(PasswordResetInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.ResetPassword(model.Email);
                    return Json(new { success = true, message = "You have been sent a message to verify your password reset at " + model.Email.ToString() });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult JsonSendUsername(SendUsernameReminderInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.SendUsernameReminder(model.Email);
                    return Json(new { success = true, email = model.Email.ToString(), message = "Sent user name to " + model.Email.ToString() });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult JsonCloseAccount(string button)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.DeleteAccount(User.Identity.Name))
                    {
                        return Json(new { success = true, redirect = "/UserAccount/Logout" });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error closing your account");
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult JsonChangePassword(ChangePasswordInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangePassword(User.Identity.Name, model.OldPassword, model.NewPassword))
                    {
                        return Json(new { success = true, message = "Your password change was processed successfully. An email confirmation was sent." });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error changing password");
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public JsonResult JsonChangePasswordFromResetKey(ChangePasswordFromResetKeyInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangePasswordFromResetKey(model.Key, model.Password))
                    {
                        return Json(new { success = true, message = "Your password change was processed successfully. An email confirmation was sent. You can now login with this new password." });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error changing password. The key may be invalid or out of date. Please try again.");
                    }
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult JsonChangeUsername(ChangeUsernameInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.userAccountService.ChangeUsername(User.Identity.Name, model.NewUsername);
                    this.authSvc.SignIn(model.NewUsername);
                    return Json(new { success = true, redirect = "/UserAccount/" });
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }


            // If we got this far, something failed
            return Json(new { errors = GetErrorsFromModelState() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult JsonChangeEmailRequest(ChangeEmailRequestInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (this.userAccountService.ChangeEmailRequest(User.Identity.Name, model.NewEmail))
                    {
                        return Json(new { success = true, message = "Your email change verification request was sent to the new email ("+model.NewEmail+").  You will be required to verify with password." });
                    }

                    ModelState.AddModelError("", "Error requesting email change.");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError("", ex.Message);

MembershipReboot.HotTowel/Controllers/HotTowelController.cs
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Controllers
{
    public class HotTowelController : Controller
    {
        //
        // GET: /HotTowel/

        public ActionResult Index()
        {
            return View();
        }

    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/ConfirmEmail.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ChangeEmailFromKeyInputModel
@{
    ViewBag.Title = "Confirm Email Change";
}

@Html.Partial("_ChangeEmailFromKey", Model)

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/ConfirmPassword.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ChangePasswordFromResetKeyInputModel
@{
    ViewBag.Title = "Reset Password";
}

@Html.Partial("_ChangePasswordFromResetKey", Model)

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/RegisterConfirm.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ResponseModel
@{
    ViewBag.Title = "Registration";
    var wasSuccessful = Model.success;
    var action = Model.action;
}

@if (action == "RegisterCancel")
{
    if (wasSuccessful)
    {
    <div class="alert alert-success">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-up"></i>Account Closed!</h4>

            <p>Your Account has been closed.</p>
            <p>
                Click @Html.ActionLink("here", "Index") to re-register or login with a different account.
            </p>
        </div>
    </div>
    }
    else
    {
    <div class="alert alert-error">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-down"></i>Error.</h4>

            <p>
                There was an error cancelling your account.
            </p>
            <p>
                If you would like to try again, click 
        @Html.ActionLink("here", "Index").
            </p>
        </div>
    </div>
    }
}
else if (action == "RegisterConfirm")
{
    if (wasSuccessful)
    {
    <div class="alert alert-success">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-up"></i>Congratulations!</h4>

            <p>Your account has been confirmed. You may login now.</p>
            <p>
                Click @Html.ActionLink("here", "Index") to sign in.
            </p>
        </div>
    </div>
    }
    else
    {
    <div class="alert alert-error">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-down"></i>Error Confirming your Registration.</h4>

            <p>
                There was an error confirming the registration. If you have already confirmed your account
        then you should recieve a confirmation email and should be able to login 
        @Html.ActionLink("here", "Index").
            </p>
        </div>
    </div>
    }
}
else if (action == "PasswordReset")
{
    if (wasSuccessful)
    {
    <div class="alert alert-success">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-up"></i>Congratulations!</h4>

            <p>Your password has been successfully changed. You may login now.</p>
            <p>
                Click @Html.ActionLink("here", "Index") to sign in.
            </p>
        </div>
    </div>
    }
    else
    {
    <div class="alert alert-error">
        <div class="container-fluid">
            <h4><i class="icon-thumbs-down"></i>Error Confirming your Registration.</h4>

            <p>
                There was an error with submitting you password change request. If you have already confirmed your password
        then you should recieve a confirmation email and should be able to login 
        @Html.ActionLink("here", "Index").
            </p>
        </div>
    </div>
    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_Authentication.cshtml
    <ul class="nav nav-tabs">
        <li class="active"><a href="#loginPanel" data-toggle="tab">Login</a></li>
        <li ><a id="showRegister" href="#registerPanel" data-toggle="tab">Register</a></li>
        <li ><a id="showSendUsername" href="#sendUsernamePanel" data-toggle="tab">Forgot Username</a></li>
        <li ><a id="showResetPassword" href="#resetPasswordPanel" data-toggle="tab">Reset Password</a></li>
    </ul>
<div class="tabbable tabs-left">
    <div class="tab-content">
        <div class="tab-pane active" id="loginPanel">
           <div class="container-fluid well">
                @Html.Partial("_Login", new MembershipReboot.HotTowel.Areas.UserAccount.Models.LoginInputModel())
            </div>
        </div>
        <div class="tab-pane" id="registerPanel">
            <div class="container-fluid well">
                @Html.Partial("_Register", new MembershipReboot.HotTowel.Areas.UserAccount.Models.RegisterInputModel())
            </div>
        </div>
        <div class="tab-pane" id="sendUsernamePanel">
            <div class="container-fluid well">
                @Html.Partial("_SendUsernameReminder", new MembershipReboot.HotTowel.Areas.UserAccount.Models.SendUsernameReminderInputModel())
            </div>
        </div>
        <div class="tab-pane" id="resetPasswordPanel">
            <div class="container-fluid well">
                @Html.Partial("_PasswordReset", new MembershipReboot.HotTowel.Areas.UserAccount.Models.PasswordResetInputModel())
            </div>
        </div>
    </div>
</div>

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_ChangePassword.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ChangePasswordInputModel

@using (Html.BeginForm("JsonChangePassword", "Membership", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "changePasswordForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Change Password</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Send Request" class="btn btn-primary" />
            </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_ChangePasswordFromResetKey.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ChangePasswordFromResetKeyInputModel

@using (Html.BeginForm("JsonChangePasswordFromResetKey", "Membership", FormMethod.Post, new { id = "changePasswordFromResetKeyForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Change Password from Reset Key</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Change Password" class="btn btn-primary" />
            </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_ChangeUsername.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.ChangeUsernameInputModel

@using (Html.BeginForm("JsonChangeUsername", "Membership", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "changeUsernameForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Change Username</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Send Request" class="btn btn-primary" />
            </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_Login.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.LoginInputModel

@using (Html.BeginForm("JsonLogin", "Membership", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "loginForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Sign In</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Log in" class="btn btn-primary" />
            </div>
        </div>

        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_LogoffMessage.cshtml
    <div class="alert alert-info">
        <h4>Important!</h4>
        <div class="container-fluid">
            You are already logged in as @User.Identity.Name<br />
            If you accessed this site on someone elses computer, please sign out.<br />
            If you are not @User.Identity.Name, please
            <br />
            @Html.ActionLink("Sign Off", "Index", "Logout",new RouteValueDictionary(new {area="UserAccount"}), new Dictionary<string, object>() { { "class", "btn btn-primary" } })
        </div>
    </div>

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_PasswordReset.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.PasswordResetInputModel

@using (Html.BeginForm("JsonResetPassword", "Membership", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "passwordResetForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Reset Password</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Send Request" class="btn btn-primary" />
            </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_Register.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.RegisterInputModel
@{
    var model = Model;
}
@using (Html.BeginForm("JsonRegister", "Membership", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { Id = "registerForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Registration Form</legend>
                @Html.EditorForModel()
                <div class="control-group">
            <div class="controls">
            <input type="submit" value="Sign up" class ="btn btn-primary" />
        </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_SendUsernameReminder.cshtml
@model MembershipReboot.HotTowel.Areas.UserAccount.Models.SendUsernameReminderInputModel

@using (Html.BeginForm("JsonSendUsername", "Membership", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "sendUsernameReminderForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Send Username</legend>
        @Html.EditorForModel()
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Send Username" class="btn btn-primary" />
            </div>
        </div>
        <div class="alert alert-success" style="display:none">
            <strong>Success!</strong>&nbsp;<span></span>
        </div>
        @Html.ValidationSummary()
    </fieldset>
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/_UserSettings.cshtml
@if (User.Identity.IsAuthenticated)
{
    using (Html.BeginForm(null, null, FormMethod.Post, new Dictionary<string, object>() { { "class", "form-inline" } }))
    {
    <fieldset>
        <legend>@ViewBag.Title</legend>
        <div class="control-group">
            <label class="control-label" for="gender">Gender</label>
            <div class="controls">
                <select id="gender" name="gender">
                    <option value="">-not set-</option>
                    <option value="male">male</option>
                    <option value="female">female</option>
                </select>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button class="btn btn-primary">Add/Change Gender</button>
            </div>
        </div>
    </fieldset>
    }

}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Login/index.cshtml
@{
    ViewBag.Title = "Account";
    //ViewBag.ReturnUrl = Html.Action("Index", "HotTowel", new { area = "" });
    ViewBag.ReturnUrl = Request.QueryString["ReturnUrl"];
}
@functions{
    public string GetAntiForgeryToken()
    {
        string cookieToken, formToken;
        AntiForgery.GetTokens(null, out cookieToken, out formToken);
        return cookieToken + ":" + formToken;
    }
}
<div id="main-content">
    @if (@User.Identity.IsAuthenticated)
    {
        @Html.Partial("_Authenticated")
    }
    else
    {
        @Html.Partial("_Authentication")
    }
</div>
@if (@User.Identity.IsAuthenticated)
{
    <input id="antiForgeryToken" type="hidden" value="@GetAntiForgeryToken()" />
@section Claims {
    <h3>Your Claims</h3>
    <dl>
        @foreach (var claim in System.Security.Claims.ClaimsPrincipal.Current.Claims)
        {
            <dt>@claim.Type</dt>
            <dd>@claim.Value</dd>
            <dd>@claim.Issuer</dd>
        }
    </dl>
}
    
}