MembershipReboot.HotTowel/Areas/UserAccount/Controllers/LogoutController.cs
using BrockAllen.MembershipReboot;
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Areas.UserAccount.Controllers
{
    public class LogoutController : Controller
    {
        ClaimsBasedAuthenticationService authSvc;
        public LogoutController(ClaimsBasedAuthenticationService authSvc)
        {
            this.authSvc = authSvc;
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.authSvc != null)
                {
                    this.authSvc.Dispose();
                    this.authSvc = null;
                }
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                authSvc.SignOut();
                return RedirectToAction("Index");
            }
            
            return View();
        }

    }
}

MembershipReboot.HotTowel/Controllers/HotTowelController.cs
using System.Web.Mvc;

namespace MembershipReboot.HotTowel.Controllers
{
    public class HotTowelController : Controller
    {
        //
        // GET: /HotTowel/

        public ActionResult Index()
        {
            return View();
        }

    }
}

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_EndScripts.cshtml
<!-- jQuery -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
<!-- Bootstrap -->
@Scripts.Render("~/bundles/login")

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_Header.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>@ViewBag.Title</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
@*Main Boilerplate Css*@
@*Bootstrap Css*@
@Styles.Render("~/Content/css/bs/boilerplate")
@*Padding to clear Menu bar*@
<style type="text/css">
    body {
        padding-top: 60px;
        padding-bottom: 40px;
    }
</style>
@*Header*@
@Scripts.Render("~/bundles/modernizr")

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
@{Html.RenderPartial("~/Areas/UserAccount/Views/Shared/_Header.cshtml");}
</head>
<body>
@{Html.RenderPartial("_UserAccountMenu");}
<!-- Modal -->
@{Html.RenderPartial("_ModalUserInformation");}

    <div class="Container-fluid">
        <div class="row-fluid">
            <div class="span2">
            <!--[if lt IE 7]>
                <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to run this site.</p>
            <![endif]-->
            </div>
            <div class="span10">
                <div class="span8">
                    @RenderBody()
                </div>
                <div class="span2"></div>
            </div>
        </div>
        @*This next section only shows when logged in and there is a Claims section in the View*@
        @if (IsSectionDefined("Claims") && (User.Identity.IsAuthenticated)) {
        <div class="row-fluid">
            <div class="span2"></div>
            <div class="span10">
                @RenderSection("Claims",false)
            </div>
        </div>
        }
    </div>
    <!-- /container -->
@{Html.RenderPartial("~/Areas/UserAccount/Views/Shared/_EndScripts.cshtml");}
@{Html.RenderPartial("~/Views/Shared/_GoogleAnalytics.cshtml");}
</body>
</html>

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_ModalUserInformation.cshtml
    <div id="modalUserInformation" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">User Information for @User.Identity.Name</h3>
        </div>
        <div class="modal-body">
            <img src="~/Content/themes/base/images/ui-icons_888888_256x240.png" />
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    </div>

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_UserAccountMenu.cshtml
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="#">@ViewBag.Title</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active">@Html.ActionLink("Home", "Index", "HotTowel", new { area = ""},null)</li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
                <div class="container">
                    <a href="#modalUserInformation" role="link" class="pull-right" data-toggle="modal"><i class="icon-question-sign icon-white"></i></a>
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            @{Html.RenderPartial("_UserMenuSection");}
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
    </div>

MembershipReboot.HotTowel/Areas/UserAccount/Views/Shared/_UserMenuSection.cshtml
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> @(null!=User.Identity.Name&&string.Empty!=User.Identity.Name?"Account ("+User.Identity.Name+")":"Account") <b class="caret"></b></a>
                            <ul class="dropdown-menu pull-right">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-header">Status (@User.Identity.Name)</li>
                                    <li>@Html.ActionLink("Sign Out", "Index", "Logout", new { area = "UserAccount" },null)</li>
                                    <li><a href="#settingsPanel" data-toggle="tab">Account Settings</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">-Account Help-</li>
                
                                    <li><a href="#changePasswordPanel" data-toggle="tab">Change Password</a></li>
                                    <li><a href="#changeUsernamePanel" data-toggle="tab">Change Username</a></li>
                                    <li><a href="#changeEmailPanel" data-toggle="tab">Change Email</a></li>
                                    <li><a href="#closeAccountPanel" data-toggle="tab">Close Account</a></li>
                                }
                                else
                                {
                                    <li class="nav-header">
                                        <div class="text-error">Status (Off)</div>
                                    </li>
                                    <li><a href="#loginPanel" data-toggle="tab">Login</a></li>
                                    <li class="divider" ></li>
                                    <li class="nav-header">-Forgot-</li>
                                    <li><a href="#sendUsernamePanel" data-toggle="tab">Email User Name</a></li>
                                    <li><a href="#resetPasswordPanel" data-toggle="tab">Reset Password</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">-Registration-</li>
                                    <li><a href="#registerPanel" data-toggle="tab">Register</a></li>
                                }
                            </ul>
                        </li>